server:
  port: 8082 #服务端口
myspcloud:
  item:
    url: http://127.0.0.1:8081/item/
spring:
  application:
    #服务名
    name: app-order
#服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://zpc:123456@127.0.0.1:8100/eureka,http://zpc:123456@127.0.0.1:9100/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-id-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
app-item:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#开启hystrix断路器
feign:
  hystrix:
    enabled: true